# Generated by Django 5.0.7 on 2024-08-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lastname', models.CharField(blank=True, max_length=56, null=True)),
                ('ctg_name', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='static/main_images')),
                ('short_descriptions_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('short_descriptions_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('short_descriptions_eng', models.CharField(blank=True, max_length=256, null=True)),
                ('data', models.DateTimeField()),
                ('post_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Information_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=128)),
                ('title_eng', models.CharField(max_length=128)),
                ('title_ru', models.CharField(max_length=128)),
                ('short_title_uz', models.CharField(max_length=500)),
                ('short_title_ru', models.CharField(max_length=500)),
                ('short_title_eng', models.CharField(max_length=500)),
                ('video_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=56)),
                ('title_ru', models.CharField(max_length=56)),
                ('title_uz', models.CharField(max_length=56)),
                ('short_title_eng', models.CharField(max_length=500)),
                ('short_title_ru', models.CharField(max_length=500)),
                ('short_title_uz', models.CharField(max_length=500)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/main_images')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/main_images')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/main_images')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='static/main_images')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_month', models.IntegerField(blank=True, default=0, null=True)),
                ('price_years', models.IntegerField(blank=True, default=0, null=True)),
                ('title1_uz', models.CharField(max_length=256)),
                ('title2_uz', models.CharField(max_length=256)),
                ('title3_uz', models.CharField(max_length=256)),
                ('title4_uz', models.CharField(max_length=256)),
                ('title5_uz', models.CharField(max_length=256)),
                ('title1_ru', models.CharField(max_length=256)),
                ('title2_ru', models.CharField(max_length=256)),
                ('title3_ru', models.CharField(max_length=256)),
                ('title4_ru', models.CharField(max_length=256)),
                ('title5_ru', models.CharField(max_length=256)),
                ('title1_eng', models.CharField(max_length=256)),
                ('title2_eng', models.CharField(max_length=256)),
                ('title3_eng', models.CharField(max_length=256)),
                ('title4_eng', models.CharField(max_length=256)),
                ('title5_eng', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_experience', models.IntegerField(blank=True, default=2000, null=True)),
                ('customers_worldwide', models.IntegerField(blank=True, default=2000, null=True)),
                ('project_completed', models.IntegerField(blank=True, default=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=128)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lastname', models.CharField(blank=True, max_length=56, null=True)),
                ('job_name', models.CharField(blank=True, max_length=182, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/main_images')),
            ],
        ),
    ]
